package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// write puts files under a temp root and returns the root and their paths.
func write(t *testing.T, files map[string]string) (string, []string) {
	t.Helper()
	root := t.TempDir()
	var rels []string
	for rel, src := range files {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
		rels = append(rels, rel)
	}
	return root, rels
}

// branchy has cyclomatic complexity n+1 and cognitive complexity n: n
// sequential ifs at nesting level 0.
func branchy(name string, n int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "func %s(x int) int {\n", name)
	for i := 0; i < n; i++ {
		fmt.Fprintf(&b, "\tif x == %d {\n\t\tx++\n\t}\n", i)
	}
	b.WriteString("\treturn x\n}\n")
	return b.String()
}

// long is a function of exactly n lines, `func` to closing brace.
func long(name string, n int) string {
	return "func " + name + "() {\n" + strings.Repeat("\t_ = 0\n", n-2) + "}\n"
}

func TestThresholdsAreStrictlyGreaterThan(t *testing.T) {
	src := "package p\n\n" +
		branchy("atCyclo", maxCyclomatic-1) + // cyclomatic 30: not over
		branchy("overCyclo", maxCyclomatic) + // cyclomatic 31, cognitive 30
		branchy("atCognit", maxCognitive) + // cognitive 40: not over; cyclomatic 41: over
		branchy("overCognit", maxCognitive+1) + // cognitive 41
		long("atLen", maxFuncLines) +
		long("overLen", maxFuncLines+1)
	root, rels := write(t, map[string]string{"pkg/p/p.go": src})
	m, err := measureFiles(root, rels, "")
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]Func{}
	for _, f := range m.Over {
		got[f.Key] = f
	}
	for _, name := range []string{"atCyclo", "atLen"} {
		if _, ok := got["pkg/p "+name]; ok {
			t.Errorf("%s is at a threshold, not over it, but was listed", name)
		}
	}
	if f := got["pkg/p overCyclo"]; f.Cyclomatic != maxCyclomatic+1 || f.Cognitive != maxCyclomatic {
		t.Errorf("overCyclo: cyclomatic %d cognitive %d", f.Cyclomatic, f.Cognitive)
	}
	if f := got["pkg/p overLen"]; f.Lines != maxFuncLines+1 {
		t.Errorf("overLen: %d lines", f.Lines)
	}
	tot := m.Totals
	// Over cyclomatic: overCyclo (31), atCognit (41), overCognit (42).
	// Over cognitive: overCognit only. Over length: overLen only.
	if tot.OverCyclomatic != 3 || tot.OverCognitive != 1 || tot.OverFuncLines != 1 {
		t.Errorf("over cyclomatic/cognitive/lines = %d/%d/%d, want 3/1/1",
			tot.OverCyclomatic, tot.OverCognitive, tot.OverFuncLines)
	}
	if tot.Funcs != 6 {
		t.Errorf("funcs = %d, want 6", tot.Funcs)
	}
}

func TestTokensAreBytesOverFourAndFileSizeLines(t *testing.T) {
	big := "package p\n\nvar s = `" + strings.Repeat("x", 4*maxFileTokens) + "`\n"      // just over 25k tokens
	warn := "package p\n\nvar w = `" + strings.Repeat("x", 4*warnFileTokens) + "`\n"    // just over 15k tokens
	lines := "package p\n\n" + strings.Repeat("var _ = 0\n", maxFileLines-2) + "// x\n" // 1,001 lines
	root, rels := write(t, map[string]string{"a/big.go": big, "a/warn.go": warn, "a/lines.go": lines})
	m, err := measureFiles(root, rels, "")
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range m.Files {
		src, _ := os.ReadFile(filepath.Join(root, f.Path))
		if f.Tokens != len(src)/4 {
			t.Errorf("%s: %d tokens, want %d (bytes/4)", f.Path, f.Tokens, len(src)/4)
		}
	}
	tot := m.Totals
	if tot.FilesOverTokens != 1 || tot.FilesOverTokensWarn != 2 || tot.FilesOverLines != 1 {
		t.Errorf("over 25k/15k tokens, over 1000 lines = %d/%d/%d, want 1/2/1",
			tot.FilesOverTokens, tot.FilesOverTokensWarn, tot.FilesOverLines)
	}
}

func TestWhatCountsWhere(t *testing.T) {
	// No research package is left in the repo; give the fixture one.
	defer func(old []string) { researchPrefixes = old }(researchPrefixes)
	researchPrefixes = []string{"pkg/lab"}
	over := branchy("Hot", maxCognitive+1)
	root, rels := write(t, map[string]string{
		"pkg/p/p.go":          "package p\n\n" + over,
		"pkg/p/p_test.go":     "package p\n\n" + branchy("TestHot", maxCognitive+1),
		"pkg/p/gen.go":        "// Code generated by x. DO NOT EDIT.\n\npackage p\n\n" + branchy("Gen", 99),
		"pkg/p/tool.go":       "//go:build ignore\n\npackage main\n\n" + branchy("Tool", 99),
		"pkg/lab/l.go":        "package lab\n\n" + branchy("Research", 99),
		"pkg/p/testdata/x.go": "package x\n\n" + branchy("Fixture", 99),
	})
	m, err := measureFiles(root, rels, "")
	if err != nil {
		t.Fatal(err)
	}
	tot := m.Totals
	if tot.Files != 1 || tot.OverCognitive != 1 {
		t.Errorf("headline: %d files, %d over cognitive; want only pkg/p/p.go", tot.Files, tot.OverCognitive)
	}
	if tot.Test.Files != 1 || tot.Test.OverCognitive != 1 {
		t.Errorf("test: %d files, %d over cognitive; want 1, 1", tot.Test.Files, tot.Test.OverCognitive)
	}
	if m.ResearchTot.Files != 1 || m.ResearchTot.OverCognitive != 1 {
		t.Errorf("research: %d files, %d over; want 1, 1", m.ResearchTot.Files, m.ResearchTot.OverCognitive)
	}
	if len(m.Over) != 1 || m.Over[0].Key != "pkg/p Hot" {
		t.Errorf("over_threshold = %+v, want only pkg/p Hot", m.Over)
	}
	if len(m.TopCognitive) != 1 || m.TopCognitive[0].Key != "pkg/p Hot" {
		t.Errorf("top_cognitive = %+v, want only pkg/p Hot", m.TopCognitive)
	}
}

func TestFuncKeys(t *testing.T) {
	src := "package p\n\ntype T struct{}\ntype G[K any] struct{}\n\n" +
		"func F() {}\nfunc (T) V() {}\nfunc (*T) P() {}\nfunc (g *G[K]) Q() {}\n"
	root, rels := write(t, map[string]string{"x/p.go": src})
	m, err := measureFiles(root, rels, "")
	if err != nil {
		t.Fatal(err)
	}
	var keys []string
	for _, f := range m.TopCognitive {
		keys = append(keys, f.Key)
	}
	want := "x (*G).Q,x (*T).P,x F,x T.V" // all cognitive 0, so sorted by key
	if got := strings.Join(keys, ","); got != want {
		t.Errorf("keys = %s, want %s", got, want)
	}
}
